/*import type { Movie, Actor, Genre, Collection, Director } from "@/types";

const img = (id: number) => `https://picsum.photos/seed/movie-${id}/600/900`;
const bd = (id: number) => `https://picsum.photos/seed/backdrop-${id}/1280/720`;
const pf = (id: number) => `https://picsum.photos/seed/actor-${id}/400/600`;

export const genres: Genre[] = [
  { id: "g1", name: "Action", slug: "action", movieCount: 18 },
  { id: "g2", name: "Drama", slug: "drama", movieCount: 24 },
  { id: "g3", name: "Sci-Fi", slug: "sci-fi", movieCount: 12 },
  { id: "g4", name: "Crime", slug: "crime", movieCount: 9 },
  { id: "g5", name: "Thriller", slug: "thriller", movieCount: 14 },
  { id: "g6", name: "Comedy", slug: "comedy", movieCount: 16 },
  { id: "g7", name: "Adventure", slug: "adventure", movieCount: 10 },
  { id: "g8", name: "Fantasy", slug: "fantasy", movieCount: 7 },
];

export const directors: Director[] = [
  { id: "d1", name: "Christopher Nolan", profileUrl: pf(101), biography: "British-American filmmaker known for blockbusters with complex storytelling.", knownFor: ["Inception", "The Dark Knight", "Interstellar", "Oppenheimer"] },
  { id: "d2", name: "Rajkumar Hirani", profileUrl: pf(102), biography: "Indian film director known for 3 Idiots, PK, and Munna Bhai.", knownFor: ["3 Idiots", "PK", "Munna Bhai M.B.B.S."] },
  { id: "d3", name: "S.S. Rajamouli", profileUrl: pf(103), biography: "Indian director known for Baahubali and RRR.", knownFor: ["Baahubali", "RRR", "Eega"] },
  { id: "d4", name: "Denis Villeneuve", profileUrl: pf(104), biography: "Canadian filmmaker known for Dune and Blade Runner 2049.", knownFor: ["Dune", "Blade Runner 2049", "Arrival"] },
];

export const collections: Collection[] = [
  { id: "c1", name: "The Dark Knight Trilogy", description: "Christopher Nolan's acclaimed Batman trilogy.", posterUrl: img(100), movieIds: ["m2"] },
  { id: "c2", name: "Dune Saga", description: "Denis Villeneuve's epic adaptation.", posterUrl: img(101), movieIds: ["m4"] },
  { id: "c3", name: "Baahubali Collection", description: "S.S. Rajamouli's epic Indian drama.", posterUrl: img(102), movieIds: ["m8"] },
  { id: "c4", name: "Indian Cinema Essentials", description: "Must-watch films from Bollywood.", posterUrl: img(103), movieIds: ["m5", "m6", "m9"] },
];

export const actors: Actor[] = [
  { id: "a1", name: "Leonardo DiCaprio", alsoKnownAs: ["Leo"], biography: "American actor and film producer. Known for biopics and period films with an Academy Award, BAFTA, and three Golden Globes. Rose to fame with Titanic (1997).", birthday: "1974-11-11", birthplace: "Los Angeles, California, USA", profileUrl: pf(1), knownForDepartment: "Acting", placeOfBirth: "Los Angeles, California, USA", nationality: "American", filmography: [{ movieId: "m1", title: "Inception", character: "Dom Cobb", year: 2010, posterUrl: img(1), rating: 8.8 }, { movieId: "m3", title: "Interstellar", character: "Cooper", year: 2014, posterUrl: img(3), rating: 8.3 }], awards: [{ name: "Academy Award", year: 2016, category: "Best Actor", won: true }], socialMedia: [{ platform: "Instagram", handle: "@leonardodicaprio", url: "#" }], gallery: [pf(11), pf(12)], trivia: ["Named after Leonardo da Vinci."], externalLinks: [{ label: "IMDb", url: "#" }] },
  { id: "a2", name: "Shah Rukh Khan", alsoKnownAs: ["SRK", "King Khan"], biography: "Indian actor and producer in Hindi films. Referred to as 'Baadshah of Bollywood' with 14 Filmfare Awards and Padma Shri.", birthday: "1965-11-02", birthplace: "New Delhi, India", profileUrl: pf(2), knownForDepartment: "Acting", placeOfBirth: "New Delhi, India", nationality: "Indian", filmography: [{ movieId: "m5", title: "3 Idiots", character: "Rancho", year: 2009, posterUrl: img(9), rating: 8.4 }], awards: [{ name: "Filmfare Award", year: 1994, category: "Best Actor", won: true }], socialMedia: [{ platform: "Twitter", handle: "@iamsrk", url: "#" }], gallery: [pf(21), pf(22)], trivia: ["Owns Red Chillies Entertainment."], externalLinks: [{ label: "IMDb", url: "#" }] },
  { id: "a3", name: "Christian Bale", alsoKnownAs: [], biography: "British actor known for versatility and physical transformations. Academy Award and two Golden Globe Awards.", birthday: "1974-01-30", birthplace: "Haverfordwest, Wales, UK", profileUrl: pf(3), knownForDepartment: "Acting", placeOfBirth: "Haverfordwest, Wales", nationality: "British", filmography: [{ movieId: "m2", title: "The Dark Knight", character: "Bruce Wayne / Batman", year: 2008, posterUrl: img(2), rating: 9.0 }], awards: [{ name: "Academy Award", year: 2011, category: "Best Supporting Actor", won: true }], socialMedia: [], gallery: [pf(31)], trivia: ["Gained 40 pounds for American Hustle."], externalLinks: [{ label: "IMDb", url: "#" }] },
  { id: "a4", name: "Aamir Khan", alsoKnownAs: ["Mr. Perfectionist"], biography: "Indian actor and filmmaker with 9 Filmfare Awards and Padma Bhushan. Known for versatility and perfectionism.", birthday: "1965-03-14", birthplace: "Mumbai, India", profileUrl: pf(4), knownForDepartment: "Acting", placeOfBirth: "Mumbai, India", nationality: "Indian", filmography: [{ movieId: "m5", title: "3 Idiots", character: "Ranchoddas Chanchad", year: 2009, posterUrl: img(9), rating: 8.4 }, { movieId: "m6", title: "Dangal", character: "Mahavir Singh Phogat", year: 2016, posterUrl: img(11), rating: 8.3 }], awards: [{ name: "Padma Bhushan", year: 2010, category: "Civilian Honor", won: true }], socialMedia: [], gallery: [pf(41)], trivia: ["Refuses to attend award ceremonies."], externalLinks: [{ label: "IMDb", url: "#" }] },
  { id: "a5", name: "Prabhas", alsoKnownAs: [], biography: "Indian actor in Telugu cinema. Known for Baahubali franchise, one of the highest-paid actors in Indian cinema.", birthday: "1979-10-23", birthplace: "Chennai, India", profileUrl: pf(5), knownForDepartment: "Acting", placeOfBirth: "Chennai, India", nationality: "Indian", filmography: [{ movieId: "m8", title: "Baahubali 2: The Conclusion", character: "Mahendra Baahubali", year: 2017, posterUrl: img(15), rating: 8.2 }, { movieId: "m9", title: "RRR", character: "Bheem", year: 2022, posterUrl: img(17), rating: 7.8 }], awards: [{ name: "Nandi Award", year: 2004, category: "Best Actor", won: true }], socialMedia: [], gallery: [pf(51)], trivia: ["Spent 5 years on Baahubali franchise."], externalLinks: [{ label: "IMDb", url: "#" }] },
  { id: "a6", name: "Florence Pugh", alsoKnownAs: [], biography: "English actress with Academy Award and BAFTA nominations. Breakthrough in 2019 with Midsommar and Little Women.", birthday: "1996-01-03", birthplace: "Oxford, England, UK", profileUrl: pf(6), knownForDepartment: "Acting", placeOfBirth: "Oxford, England", nationality: "British", filmography: [{ movieId: "m4", title: "Dune: Part Two", character: "Princess Irulan", year: 2024, posterUrl: img(7), rating: 8.6 }, { movieId: "m10", title: "Oppenheimer", character: "Jean Tatlock", year: 2023, posterUrl: img(19), rating: 8.4 }], awards: [{ name: "BAFTA", year: 2020, category: "Rising Star", won: true }], socialMedia: [], gallery: [pf(61)], trivia: ["Trillobite named after her."], externalLinks: [{ label: "IMDb", url: "#" }] },
];

export const movies: Movie[] = [
  { id: "m1", title: "Inception", overview: "A skilled thief who commits corporate espionage by infiltrating the subconscious is offered a chance to regain his old life through inception.", posterUrl: img(1), backdropUrl: bd(1), releaseDate: "2010-07-16", year: 2010, runtime: 148, rating: 8.8, voteCount: 35000, genres: ["Action", "Sci-Fi", "Thriller"], languages: ["English"], budget: 160000000, revenue: 836800000, tagline: "Your mind is the scene of the crime.", status: "Released", trailerUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0", cast: [{ id: "c1", actorId: "a1", character: "Dom Cobb", order: 0 }], crew: [{ id: "cr1", name: "Christopher Nolan", job: "Director", department: "Directing" }], productionCompanies: [{ id: "p1", name: "Warner Bros." }], streamingProviders: ["Netflix", "HBO Max"], awards: [{ id: "aw1", name: "Academy Award", year: 2011, category: "Best Cinematography", won: true }], recommendations: ["m2", "m3", "m4"], similar: ["m3", "m4", "m10"], industry: "Hollywood" },
  { id: "m2", title: "The Dark Knight", overview: "Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and DA Harvey Dent, facing the Joker's reign of chaos.", posterUrl: img(2), backdropUrl: bd(2), releaseDate: "2008-07-18", year: 2008, runtime: 152, rating: 9.0, voteCount: 30000, genres: ["Action", "Crime", "Drama"], languages: ["English"], budget: 185000000, revenue: 1006000000, tagline: "Why so serious?", status: "Released", trailerUrl: "https://www.youtube.com/watch?v=EXeTwQqrcyY", cast: [{ id: "c3", actorId: "a3", character: "Bruce Wayne / Batman", order: 0 }], crew: [{ id: "cr4", name: "Christopher Nolan", job: "Director", department: "Directing" }], productionCompanies: [{ id: "p1", name: "Warner Bros." }], streamingProviders: ["HBO Max", "Netflix"], awards: [{ id: "aw3", name: "Academy Award", year: 2009, category: "Best Supporting Actor", won: true }], recommendations: ["m1", "m3", "m10"], similar: ["m1", "m10"], industry: "Hollywood" },
  { id: "m3", title: "Interstellar", overview: "A group of explorers use a rift in space-time to surpass limits on human space travel and conquer interstellar distances.", posterUrl: img(3), backdropUrl: bd(3), releaseDate: "2014-11-07", year: 2014, runtime: 169, rating: 8.3, voteCount: 28000, genres: ["Adventure", "Drama", "Sci-Fi"], languages: ["English"], budget: 165000000, revenue: 773000000, tagline: "Mankind was born on Earth.", status: "Released", trailerUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E", cast: [{ id: "c5", actorId: "a1", character: "Cooper", order: 0 }], crew: [{ id: "cr5", name: "Christopher Nolan", job: "Director", department: "Directing" }], productionCompanies: [{ id: "p1", name: "Warner Bros." }], streamingProviders: ["Netflix", "Amazon Prime"], awards: [{ id: "aw4", name: "Academy Award", year: 2015, category: "Best Visual Effects", won: true }], recommendations: ["m1", "m4", "m10"], similar: ["m1", "m4"], industry: "Hollywood" },
  { id: "m4", title: "Dune: Part Two", overview: "Paul Atreides unites with the Fremen on a path of revenge against those who destroyed his family, facing a choice between love and the universe.", posterUrl: img(4), backdropUrl: bd(4), releaseDate: "2024-03-01", year: 2024, runtime: 166, rating: 8.6, voteCount: 15000, genres: ["Action", "Adventure", "Sci-Fi"], languages: ["English"], budget: 190000000, revenue: 712000000, tagline: "Long live the fighters.", status: "Released", trailerUrl: "https://www.youtube.com/watch?v=Way9Dexny3w", cast: [{ id: "c6", actorId: "a6", character: "Princess Irulan", order: 0 }], crew: [{ id: "cr6", name: "Denis Villeneuve", job: "Director", department: "Directing" }], productionCompanies: [{ id: "p3", name: "Warner Bros." }], streamingProviders: ["HBO Max", "Netflix"], awards: [], recommendations: ["m1", "m3", "m10"], similar: ["m1", "m3"], industry: "Hollywood" },
  { id: "m5", title: "3 Idiots", overview: "Two friends search for their lost companion, revisiting college days and recalling memories of their friend who inspired them to think differently.", posterUrl: img(5), backdropUrl: bd(5), releaseDate: "2009-12-25", year: 2009, runtime: 170, rating: 8.4, voteCount: 22000, genres: ["Comedy", "Drama"], languages: ["Hindi", "English"], budget: 12000000, revenue: 60000000, tagline: "Don't be a fool, be an idiot.", status: "Released", trailerUrl: "https://www.youtube.com/watch?v=K0eDlFX9GMc", cast: [{ id: "c7", actorId: "a4", character: "Ranchoddas Chanchad", order: 0 }, { id: "c8", actorId: "a2", character: "Rancho", order: 1 }], crew: [{ id: "cr7", name: "Rajkumar Hirani", job: "Director", department: "Directing" }], productionCompanies: [{ id: "p4", name: "Vinod Chopra Films" }], streamingProviders: ["Amazon Prime", "Netflix"], awards: [{ id: "aw5", name: "Filmfare Award", year: 2010, category: "Best Film", won: true }], recommendations: ["m6", "m9"], similar: ["m6"], industry: "Bollywood" },
  { id: "m6", title: "Dangal", overview: "The true story of Mahavir Singh Phogat who trains his daughters to become India's first world-class female wrestlers.", posterUrl: img(6), backdropUrl: bd(6), releaseDate: "2016-12-23", year: 2016, runtime: 161, rating: 8.3, voteCount: 18000, genres: ["Action", "Drama"], languages: ["Hindi"], budget: 10000000, revenue: 300000000, tagline: "Mahavir Singh Phogat and his daughters.", status: "Released", trailerUrl: "https://www.youtube.com/watch?v=x_7YlGv9U1g", cast: [{ id: "c9", actorId: "a4", character: "Mahavir Singh Phogat", order: 0 }], crew: [{ id: "cr8", name: "Nitesh Tiwari", job: "Director", department: "Directing" }], productionCompanies: [{ id: "p5", name: "Aamir Khan Productions" }], streamingProviders: ["Netflix", "Amazon Prime"], awards: [], recommendations: ["m5", "m9"], similar: ["m5"], industry: "Bollywood" },
  { id: "m7", title: "Parasite", overview: "Ki-taek's family takes peculiar interest in the wealthy Parks until they get entangled in an unexpected incident.", posterUrl: img(7), backdropUrl: bd(7), releaseDate: "2019-05-30", year: 2019, runtime: 132, rating: 8.5, voteCount: 20000, genres: ["Comedy", "Drama", "Thriller"], languages: ["Korean"], budget: 11400000, revenue: 263000000, tagline: "Act like you own the place.", status: "Released", trailerUrl: "https://www.youtube.com/watch?v=5xH0HmJWcYU", cast: [], crew: [{ id: "cr9", name: "Bong Joon-ho", job: "Director", department: "Directing" }], productionCompanies: [{ id: "p6", name: "CJ Entertainment" }], streamingProviders: ["Hulu", "Amazon Prime"], awards: [{ id: "aw6", name: "Academy Award", year: 2020, category: "Best Picture", won: true }], recommendations: ["m2", "m10"], similar: ["m2"], industry: "Hollywood" },
  { id: "m8", title: "Baahubali 2: The Conclusion", overview: "When Mahendra, son of Bahubali, learns about his heritage, he begins to look for answers in the Mahishmati Kingdom.", posterUrl: img(8), backdropUrl: bd(8), releaseDate: "2017-04-28", year: 2017, runtime: 167, rating: 8.2, voteCount: 16000, genres: ["Action", "Drama", "Fantasy"], languages: ["Telugu", "Hindi"], budget: 25000000, revenue: 260000000, tagline: "The epic conclusion.", status: "Released", trailerUrl: "https://www.youtube.com/watch?v=G62HrubD340", cast: [{ id: "c10", actorId: "a5", character: "Mahendra Baahubali", order: 0 }], crew: [{ id: "cr10", name: "S.S. Rajamouli", job: "Director", department: "Directing" }], productionCompanies: [{ id: "p7", name: "Vyjayanthi Movies" }], streamingProviders: ["Netflix", "Hotstar"], awards: [], recommendations: ["m9"], similar: ["m9"], industry: "Tollywood" },
  { id: "m9", title: "RRR", overview: "A fictitious story about two legendary revolutionaries and their journey before fighting for their country in 1920s.", posterUrl: img(9), backdropUrl: bd(9), releaseDate: "2022-03-25", year: 2022, runtime: 187, rating: 7.8, voteCount: 14000, genres: ["Action", "Drama"], languages: ["Telugu", "Hindi"], budget: 72000000, revenue: 160000000, tagline: "Rise Roar Revolt.", status: "Released", trailerUrl: "https://www.youtube.com/watch?v=f_vbAtkSE9s", cast: [{ id: "c11", actorId: "a5", character: "Bheem", order: 0 }], crew: [{ id: "cr11", name: "S.S. Rajamouli", job: "Director", department: "Directing" }], productionCompanies: [{ id: "p7", name: "Vyjayanthi Movies" }], streamingProviders: ["Netflix", "ZEE5"], awards: [{ id: "aw7", name: "Academy Award", year: 2023, category: "Best Original Song", won: true }], recommendations: ["m8"], similar: ["m8"], industry: "Tollywood" },
  { id: "m10", title: "Oppenheimer", overview: "The story of J. Robert Oppenheimer's role in the atomic bomb development and the moral and political fallout.", posterUrl: img(10), backdropUrl: bd(10), releaseDate: "2023-07-21", year: 2023, runtime: 180, rating: 8.4, voteCount: 19000, genres: ["Drama", "Thriller"], languages: ["English"], budget: 100000000, revenue: 952000000, tagline: "The world forever changes.", status: "Released", trailerUrl: "https://www.youtube.com/watch?v=uYPbbksJxIg", cast: [{ id: "c12", actorId: "a6", character: "Jean Tatlock", order: 0 }], crew: [{ id: "cr12", name: "Christopher Nolan", job: "Director", department: "Directing" }], productionCompanies: [{ id: "p1", name: "Warner Bros." }], streamingProviders: ["HBO Max", "Netflix"], awards: [{ id: "aw8", name: "Academy Award", year: 2024, category: "Best Picture", won: true }], recommendations: ["m1", "m2", "m3"], similar: ["m1", "m3"], industry: "Hollywood" },
];

export const trendingSearches = ["Oppenheimer", "Dune Part Two", "Inception", "RRR", "Parasite", "Baahubali"];
